const mockResponse = {
  "kind": "Listing",
  "data": {
    "after": "t3_1balmxm",
    "dist": 25,
    "modhash": "dbpz1gu3b05f40393fd084ca919c4411fd7f874d6097dc47c8",
    "geo_filter": null,
    "children": [
      {
        "kind": "t3",
        "data": {
          "approved_at_utc": null,
          "subreddit": "mildlyinfuriating",
          "selftext": "",
          "author_fullname": "t2_7h2lii4b5",
          "saved": false,
          "mod_reason_title": null,
          "gilded": 0,
          "clicked": false,
          "title": "It won’t hurt they said.",
          "link_flair_richtext": [],
          "subreddit_name_prefixed": "r/mildlyinfuriating",
          "hidden": false,
          "pwls": 6,
          "link_flair_css_class": null,
          "downs": 0,
          "thumbnail_height": 140,
          "top_awarded_type": null,
          "hide_score": false,
          "name": "t3_1bapg3w",
          "quarantine": false,
          "link_flair_text_color": "dark",
          "upvote_ratio": 0.86,
          "author_flair_background_color": null,
          "subreddit_type": "public",
          "ups": 42296,
          "total_awards_received": 0,
          "media_embed": {},
          "thumbnail_width": 140,
          "author_flair_template_id": null,
          "is_original_content": false,
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": true,
          "is_meta": false,
          "category": null,
          "secure_media_embed": {},
          "link_flair_text": null,
          "can_mod_post": false,
          "score": 42296,
          "approved_by": null,
          "is_created_from_ads_ui": false,
          "author_premium": false,
          "thumbnail":
            "https://b.thumbs.redditmedia.com/3Pzck2CM1umluTjxc0BMSMPOx7qdTY24RJY9IUKamjQ.jpg",
          "edited": false,
          "author_flair_css_class": null,
          "author_flair_richtext": [],
          "gildings": {},
          "post_hint": "image",
          "content_categories": null,
          "is_self": false,
          "mod_note": null,
          "created": 1710011331,
          "link_flair_type": "text",
          "wls": 6,
          "removed_by_category": null,
          "banned_by": null,
          "author_flair_type": "text",
          "domain": "i.redd.it",
          "allow_live_comments": true,
          "selftext_html": null,
          "likes": null,
          "suggested_sort": null,
          "banned_at_utc": null,
          "url_overridden_by_dest": "https://i.redd.it/ptm98evmxcnc1.jpeg",
          "view_count": null,
          "archived": false,
          "no_follow": false,
          "is_crosspostable": true,
          "pinned": false,
          "over_18": false,
          "preview": {
            "images": [
              {
                "source": {
                  "url":
                    "https://preview.redd.it/ptm98evmxcnc1.jpeg?auto=webp&amp;s=b9b1aaa816d0b9b3d59ca4ea99e7a402bf2b691b",
                  "width": 3024,
                  "height": 4032,
                },
                "resolutions": [
                  {
                    "url":
                      "https://preview.redd.it/ptm98evmxcnc1.jpeg?width=108&amp;crop=smart&amp;auto=webp&amp;s=2f011335f52741a477f27c7752f4a83eab8e885a",
                    "width": 108,
                    "height": 144,
                  },
                  {
                    "url":
                      "https://preview.redd.it/ptm98evmxcnc1.jpeg?width=216&amp;crop=smart&amp;auto=webp&amp;s=f927e22129254fd0a1b4d7f00369a63bcd74f2bf",
                    "width": 216,
                    "height": 288,
                  },
                  {
                    "url":
                      "https://preview.redd.it/ptm98evmxcnc1.jpeg?width=320&amp;crop=smart&amp;auto=webp&amp;s=9d58c974dc609dfeccd3252b98ea5e3a02edc179",
                    "width": 320,
                    "height": 426,
                  },
                  {
                    "url":
                      "https://preview.redd.it/ptm98evmxcnc1.jpeg?width=640&amp;crop=smart&amp;auto=webp&amp;s=5a1bb252371acc12dc0434575fe0080046e8c5d3",
                    "width": 640,
                    "height": 853,
                  },
                  {
                    "url":
                      "https://preview.redd.it/ptm98evmxcnc1.jpeg?width=960&amp;crop=smart&amp;auto=webp&amp;s=3e27f281fe0cea4a36b2ef992a955ee01365681e",
                    "width": 960,
                    "height": 1280,
                  },
                  {
                    "url":
                      "https://preview.redd.it/ptm98evmxcnc1.jpeg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=f52501df7de8256850aadb8674a22e658d1b1036",
                    "width": 1080,
                    "height": 1440,
                  },
                ],
                "variants": {},
                "id": "BM2PFk5QFvkQX-qMP5WWR9fjg7XXelcqM6F_MQoTJbM",
              },
            ],
            "enabled": true,
          },
          "all_awardings": [],
          "awarders": [],
          "media_only": false,
          "can_gild": false,
          "spoiler": false,
          "locked": false,
          "author_flair_text": null,
          "treatment_tags": [],
          "visited": false,
          "removed_by": null,
          "num_reports": null,
          "distinguished": null,
          "subreddit_id": "t5_2ubgg",
          "author_is_blocked": false,
          "mod_reason_by": null,
          "removal_reason": null,
          "link_flair_background_color": "",
          "id": "1bapg3w",
          "is_robot_indexable": true,
          "report_reasons": null,
          "author": "Not_Enough_Shoes",
          "discussion_type": null,
          "num_comments": 6669,
          "send_replies": false,
          "whitelist_status": "all_ads",
          "contest_mode": false,
          "mod_reports": [],
          "author_patreon_flair": false,
          "author_flair_text_color": null,
          "permalink":
            "/r/mildlyinfuriating/comments/1bapg3w/it_wont_hurt_they_said/",
          "parent_whitelist_status": "all_ads",
          "stickied": false,
          "url": "https://i.redd.it/ptm98evmxcnc1.jpeg",
          "subreddit_subscribers": 7159392,
          "created_utc": 1710011331,
          "num_crossposts": 5,
          "media": null,
          "is_video": false,
        },
      },
      {
        "kind": "t3",
        "data": {
          "approved_at_utc": null,
          "subreddit": "ImTheMainCharacter",
          "selftext": "",
          "author_fullname": "t2_6wizdco2",
          "saved": false,
          "mod_reason_title": null,
          "gilded": 0,
          "clicked": false,
          "title": "Airport Man response to YouTube prank of “stolen luggage”",
          "link_flair_richtext": [
            {
              "e": "text",
              "t": "Video",
            },
          ],
          "subreddit_name_prefixed": "r/ImTheMainCharacter",
          "hidden": false,
          "pwls": 6,
          "link_flair_css_class": "",
          "downs": 0,
          "thumbnail_height": 140,
          "top_awarded_type": null,
          "hide_score": false,
          "name": "t3_1banqe1",
          "quarantine": false,
          "link_flair_text_color": "light",
          "upvote_ratio": 0.89,
          "author_flair_background_color": null,
          "ups": 20217,
          "total_awards_received": 0,
          "media_embed": {},
          "thumbnail_width": 140,
          "author_flair_template_id": null,
          "is_original_content": false,
          "user_reports": [],
          "secure_media": {
            "reddit_video": {
              "bitrate_kbps": 800,
              "fallback_url":
                "https://v.redd.it/kp52zz2vkcnc1/DASH_360.mp4?source=fallback",
              "has_audio": true,
              "height": 640,
              "width": 358,
              "scrubber_media_url":
                "https://v.redd.it/kp52zz2vkcnc1/DASH_96.mp4",
              "dash_url":
                "https://v.redd.it/kp52zz2vkcnc1/DASHPlaylist.mpd?a=1712659526%2CNWMwMzVmZTBiYmY4ZThiZGM3ODBmNDk3Mzg4YWZmMDVkMjY4YmE0MDg3NDE5OWM3OWE3YmZmMTY1M2RhZTRjNA%3D%3D&amp;v=1&amp;f=sd",
              "duration": 115,
              "hls_url":
                "https://v.redd.it/kp52zz2vkcnc1/HLSPlaylist.m3u8?a=1712659526%2CMmIzYWUyZTEzMDA4NDc3NTJiMDA5MmVmNzg2MjQ3N2Y4NTQzOTE0MWM1YTNjZjg4ZTZlYTdmOWMyYTViYzBiYg%3D%3D&amp;v=1&amp;f=sd",
              "is_gif": false,
              "transcoding_status": "completed",
            },
          },
          "is_reddit_media_domain": true,
          "is_meta": false,
          "category": null,
          "secure_media_embed": {},
          "link_flair_text": "Video",
          "can_mod_post": false,
          "score": 20217,
          "approved_by": null,
          "is_created_from_ads_ui": false,
          "author_premium": true,
          "thumbnail":
            "https://external-preview.redd.it/ZnlxZWM0MXZrY25jMWYrAoimXDMXmPaZ_J605SLCifCxymULmpdvWnG2e9VA.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=5c343ee7861c19c96628f558b122988f55d593e9",
          "edited": false,
          "author_flair_css_class": null,
          "author_flair_richtext": [],
          "gildings": {},
          "post_hint": "hosted:video",
          "content_categories": null,
          "is_self": false,
          "subreddit_type": "public",
          "created": 1710007038,
          "link_flair_type": "richtext",
          "wls": 6,
          "removed_by_category": null,
          "banned_by": null,
          "author_flair_type": "text",
          "domain": "v.redd.it",
          "allow_live_comments": true,
          "selftext_html": null,
          "likes": null,
          "suggested_sort": null,
          "banned_at_utc": null,
          "url_overridden_by_dest": "https://v.redd.it/kp52zz2vkcnc1",
          "view_count": null,
          "archived": false,
          "no_follow": false,
          "is_crosspostable": true,
          "pinned": false,
          "over_18": false,
          "preview": {
            "images": [
              {
                "source": {
                  "url":
                    "https://external-preview.redd.it/ZnlxZWM0MXZrY25jMWYrAoimXDMXmPaZ_J605SLCifCxymULmpdvWnG2e9VA.png?format=pjpg&amp;auto=webp&amp;s=52a33c9dc683a455d58c65179929a18f4b2f1bbf",
                  "width": 402,
                  "height": 720,
                },
                "resolutions": [
                  {
                    "url":
                      "https://external-preview.redd.it/ZnlxZWM0MXZrY25jMWYrAoimXDMXmPaZ_J605SLCifCxymULmpdvWnG2e9VA.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=4c509ed02feda3b67f8478c404c633b44a5f79bf",
                    "width": 108,
                    "height": 193,
                  },
                  {
                    "url":
                      "https://external-preview.redd.it/ZnlxZWM0MXZrY25jMWYrAoimXDMXmPaZ_J605SLCifCxymULmpdvWnG2e9VA.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=0b8a4774346d84610ab06476c2a8cd916617331f",
                    "width": 216,
                    "height": 386,
                  },
                  {
                    "url":
                      "https://external-preview.redd.it/ZnlxZWM0MXZrY25jMWYrAoimXDMXmPaZ_J605SLCifCxymULmpdvWnG2e9VA.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=091a0253ebd55148f733da281507a7d32d12625f",
                    "width": 320,
                    "height": 573,
                  },
                ],
                "variants": {},
                "id":
                  "ZnlxZWM0MXZrY25jMWYrAoimXDMXmPaZ_J605SLCifCxymULmpdvWnG2e9VA",
              },
            ],
            "enabled": false,
          },
          "all_awardings": [],
          "awarders": [],
          "media_only": false,
          "link_flair_template_id": "1c5eb988-aa24-11eb-825d-0e0aaddf682d",
          "can_gild": false,
          "spoiler": false,
          "locked": false,
          "author_flair_text": null,
          "treatment_tags": [],
          "visited": false,
          "removed_by": null,
          "mod_note": null,
          "distinguished": null,
          "subreddit_id": "t5_4c4j2u",
          "author_is_blocked": false,
          "mod_reason_by": null,
          "num_reports": null,
          "removal_reason": null,
          "link_flair_background_color": "#cc8b00",
          "id": "1banqe1",
          "is_robot_indexable": true,
          "report_reasons": null,
          "author": "KonradFelixCyprianus",
          "discussion_type": null,
          "num_comments": 4264,
          "send_replies": true,
          "whitelist_status": "all_ads",
          "contest_mode": false,
          "mod_reports": [],
          "author_patreon_flair": false,
          "author_flair_text_color": null,
          "permalink":
            "/r/ImTheMainCharacter/comments/1banqe1/airport_man_response_to_youtube_prank_of_stolen/",
          "parent_whitelist_status": "all_ads",
          "stickied": false,
          "url": "https://v.redd.it/kp52zz2vkcnc1",
          "subreddit_subscribers": 1263783,
          "created_utc": 1710007038,
          "num_crossposts": 10,
          "media": {
            "reddit_video": {
              "bitrate_kbps": 800,
              "fallback_url":
                "https://v.redd.it/kp52zz2vkcnc1/DASH_360.mp4?source=fallback",
              "has_audio": true,
              "height": 640,
              "width": 358,
              "scrubber_media_url":
                "https://v.redd.it/kp52zz2vkcnc1/DASH_96.mp4",
              "dash_url":
                "https://v.redd.it/kp52zz2vkcnc1/DASHPlaylist.mpd?a=1712659526%2CNWMwMzVmZTBiYmY4ZThiZGM3ODBmNDk3Mzg4YWZmMDVkMjY4YmE0MDg3NDE5OWM3OWE3YmZmMTY1M2RhZTRjNA%3D%3D&amp;v=1&amp;f=sd",
              "duration": 115,
              "hls_url":
                "https://v.redd.it/kp52zz2vkcnc1/HLSPlaylist.m3u8?a=1712659526%2CMmIzYWUyZTEzMDA4NDc3NTJiMDA5MmVmNzg2MjQ3N2Y4NTQzOTE0MWM1YTNjZjg4ZTZlYTdmOWMyYTViYzBiYg%3D%3D&amp;v=1&amp;f=sd",
              "is_gif": false,
              "transcoding_status": "completed",
            },
          },
          "is_video": true,
        },
      },
    ],
  },
};

export default mockResponse;
